eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.123:10000/eureka/,http://192.168.1.123:10001/eureka/
    healthcheck:
      enabled: true

server:
  port: 10010
  servlet:
    context-path: /

spring:
#  profiles:
#    active: local
  application:
    name: zipkin

  main:
    #允许使用相同的服务名
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai