#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/,http://127.0.0.1:8001/eureka/
    healthcheck:
      enabled: true

server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: zuul

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

zuul:
  routes:
    #将xiaobao模块路由到路径/ask/开头的的url,并且对应的服务id是client
    xiaobao:
      path: /xiaobao/**
      serviceId: client-8020
    #将tangdabao模块路由到路径/joker/开头的的url,并且对应的服务id是client
    dabao:
      path: /dabao/**
      serviceId: client-8030

#oauth鉴权配置
oauth:
  enabled: true
  check_token_url: http://127.0.0.1:9010/oauth/check_token
  authenticated_list:
    - /xiaobao/**
    - /xixi/**

logging:
  level.root: info