spring:
  application:
    name: eureka-10000

server:
  #address: 0.0.0.0
  port: 10000

eureka:
  instance:
    hostname: eureka-10000
    prefer-ip-address: true
    ip-address: 192.168.1.123
    instance-id: ${spring.application.name}:${server.port}
  client:
    #这台机器的注册信息是否允许被其它机器发现
    #registerWithEureka: false
    #向注册中心拿取注册信息
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.1.123:10001/eureka/
  #server:
    #是否开启eureka自我保护机制，网络中断eureka信息也不丢失
    #enable-self-preservation:

    healthcheck:
      enabled: true